CROSS_COMPILE ?= arm-none-eabi-
CC := $(CROSS_COMPILE)gcc
LD := $(CROSS_COMPILE)ld
SIZE := $(CROSS_COMPILE)size
OBJCOPY := $(CROSS_COMPILE)objcopy

CFLAGS += -Os
CFLAGS += -ggdb3
CFLAGS += -ffunction-sections
CFLAGS += -fdata-sections
CFLAGS += -ffreestanding
CFLAGS += -fshort-enums

CFLAGS_CPU := -mcpu=cortex-m7 -mtune=cortex-m7#-mfpu=fpv5-d16

LDFLAGS += --specs=nano.specs
LDFLAGS += --specs=nosys.specs
LDFLAGS += --gc-sections
LDFLAGS += --warn-common

