MAKEFLAGS += --no-builtin-rules
MAKEFLAGS += --warn-undefined-variables

.DEFAULT_GOAL := all

BUILDTOP ?= build
BUILDDIR = $(BUILDTOP)/$(TARGET)

GetCurrentMakefile = $(lastword $(MAKEFILE_LIST))
GetCurrentMakefileDirectory = $(dir $(call GetCurrentMakefile))
MakeObjectsDependOnCurrentMakefile = $(addprefix $(BUILDDIR)/,$(1)): $(call GetCurrentMakefile)

ifndef V
  Q := @
else
  Q:=
endif
